name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: af2c7e37-48d7-4047-adda-3b5eaabed370
          region: "Australia East"
          template: ./arm-template/resourcegroup.json
          deploymentName: rg-githubactions

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: af2c7e37-48d7-4047-adda-3b5eaabed370
          template: ./arm-template/storageaccount.json
          parameters: 
            ./arm-template/storageaccount.parameters.json
            storageAccountName=globostg002
            location="Australia East"
          deploymentMode: incremental